### ISSUE TITLE
Rewrite README.md

### ISSUE THREAD

**Issue by sano-jin** [sapphimoor/nQueens#1]
# README.md の英語が若干怪しかったので修正案（無視して良いです）

（ちょっと目を話した隙に？）まさかこんなのを書いていたとはね！

ただ良いプログラムなんだけど若干 readme の英語が怪しい気がしたので……
（せっかくこんなの作ったのならもっと多くの人に見てもらうべきだと思うし）

これがあっているかというとそれもだいぶ怪しいけど，まぁマシにはなっているんじゃないかな？

```markdown
# nQueens
A very simple _n_ queens puzzle solver written in c.

To use this program, run this in a terminal and answer the prompt `Input PROBLEM SIZE: n = ` with the size of the problem you want to solve.

Options:
- `-n` ( or `--number`) : show the answer in a (row, col) form
- `-b` ( or `--board`) : show the answer in a visualised board
```

出力はこんな感じになる．

---

# nQueens
A very simple _n_ queens puzzle solver written in c.

To use this program, run this in a terminal and answer the prompt `Input PROBLEM SIZE: n = ` with the size of the problem you want to solve.

Options:
- `-n` ( or `--number`) : show the answer in a (row, col) form
- `-b` ( or `--board`) : show the answer in a visualised board

---

（github の）マークダウンも少し覚えておくと良いと思う．
別に毎回丁寧に書く必要があるとはこれっぽっちも思わないけど，中身が力作だったらもう少し宣伝しても良いかもなぁと．

**Comment by sapphimoor** [comment]
わざわざありがとう！！！
